# Generated by Django 6.0.2 on 2026-03-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_category_status_listobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='template',
            field=models.CharField(choices=[('anime', 'Anime'), ('books', 'Books'), ('movies', 'Movies'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
